# Generated by Django 3.0.7 on 2022-03-17 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 13, 30, 23, 546530, tzinfo=utc)),
        ),
    ]
