# Generated by Django 3.0.7 on 2022-03-17 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 13, 31, 21, 631680, tzinfo=utc)),
        ),
    ]
