# Generated by Django 3.0.7 on 2022-03-17 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220317_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-last_message']},
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 13, 33, 11, 771342, tzinfo=utc)),
        ),
    ]
