# Generated by Django 3.0.7 on 2022-02-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('social_media', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
