# Generated by Django 3.0.7 on 2022-03-02 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220218_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
